### ISSUE TITLE
data labels are not up to speed with markers

### ISSUE THREAD

**Issue by imcullan** [larsac07/Motion-Highcharts-Plugin#13]
#### Expected behaviour
The data labels are supposed to be in sync with the markers.

#### Actual behaviour
The data labels lag behind the markers.

#### Live demo with steps to reproduce
Since a live dataset is required, there is no reproducible example, but there are about 10000 data points to make this graph.
http://rpubs.com/cullan/nba-play

**Comment by larsac07** [comment]
Hi, @imcullan. It's kind of hard to see what causes this without a chart configuration to look at. I cannot see why a live dataset is required to show the issue. You could simplify with only using one point, and a sequence of e.g. 5 artificial values, like this:

```
series: [{
  dataLabels: {
    enabled: true
  },
  data: [{
    sequence: [[5, 3], [6, 2], [7, 1], [8, 0], [9, 1]]
  }]
}]
```


There might be a problem with your setup, as it looks like points are not animated, while labels are. Take a look at this example with scatter: http://jsfiddle.net/larsac07/7p91obc3/2/. This works just fine, so there is no telling if you have a `Motion` problem or a Highcharts problem.

Can you at least provide the configuration you used?

**Comment by larsac07** [comment]
Closing this, as it seems you solved your issue, @imcullan: http://www.highcharts.com/blog/post/deconstructing-animated-sports-chart/ :)
