### ISSUE TITLE
Max startIndex appears to be 100

### ISSUE THREAD

**Issue by rwfilice** [larsac07/Motion-Highcharts-Plugin#14]
Please see this example jfiddle where there are 101 elements but the max startIndex is 100 no matter what it is set to:

http://jsfiddle.net/nt1mgqkh/

thanks!
Ross

**Comment by larsac07** [comment]
Yes, you are right! It looks like the `input` element assumes a `max` of `100`, and any `value` set above that is set to `100`. When `max` is set to a higher number on beforehand, it accepts a higher number. Pushing a fix now.

**Comment by larsac07** [comment]
Thank you for your report, @rwfilice :)

**Comment by rwfilice** [comment]
Thanks so much! Looks great now.
