### ISSUE TITLE
Motion doesnt work with custom/world map?

### ISSUE THREAD

**Issue by MGDSoft** [larsac07/Motion-Highcharts-Plugin#2]
First thanks for this plugin larsac!

I am trying to create a simple chart (with custom/world) with motion but it throw me this error
'Uncaught TypeError: Cannot read property 'length' of undefinedmotion.js:31 (anonymous function)
highmaps.js:22 each.Array.forEach.g'

Here is my fiddle http://jsfiddle.net/x1u57r5c/

**Comment by larsac07** [comment]
Thank you! Sorry for not answering. Was at vacation!
