### ISSUE TITLE
bubble size example

### ISSUE THREAD

**Issue by jbkunst** [larsac07/Motion-Highcharts-Plugin#5]
Hi @larsac07 

First of all thanks for this amazing plugin.

I have seen the first example you show: http://jsfiddle.net/gh/get/jquery/1.9.1/larsac07/Motion-Highcharts-Plugin/tree/master/demos/map-australia-bubbles-demo/ but I want to know if is possible to chage the bubble's position to other points (given lat and lon)

Thanks again!

**Comment by jbkunst** [comment]
Hi agin @larsac07 

Sorry to bother you, just want to know if its possible to do something like:

- https://bost.ocks.org/mike/nations/
- http://rud.is/projects/nucleard3/index.html

Regards,

**Comment by jbkunst** [comment]
Ooops I'm just saw your accident example.

**Comment by larsac07** [comment]
Hi, @jbkunst! Sorry for the late response. Yes, as you probably figured out from the [traffic accident example on highcharts.com (at the bottom of the page)](http://www.highcharts.com/blog/176-charts-in-motion) this is absolutely possible. The trick is in formatting your data :) I hope you figured it out. If not, please feel free to ask me any question regarding the plugin.
