### ISSUE TITLE
Motion bubbles 

### ISSUE THREAD

**Issue by GiovanninoPaneEvino** [larsac07/Motion-Highcharts-Plugin#8]
Hello! Would it be possible to have a small example of motion on bubbles on the x, y and z axis together? Thanks :-)
(side question : is it possible to have the default value of the time bar on one point different from the first one?Thanks X2! )

**Comment by larsac07** [comment]
Hi, @GiovanninoPaneEvino.

Q1: I presume you meant `scatter`, which can be drawn in 3D-space: http://jsfiddle.net/larsac07/5y4gq4no/2/ (I just used random values here, so feel free to put actual values. 3D bubbles in Highcharts look 3D, but the z-axis is actually the bubble size: http://www.highcharts.com/demo/bubble-3d

Q2: No, I thought it was, but apparently not. I'll try and add it.

**Comment by larsac07** [comment]
@GiovanninoPaneEvino I just added a new option `startIndex` (commit 13a7928), which controls the sequence index to start with. Adding it to the wiki. Thanks!
